apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-k8s.fullname" . }}
  labels:
{{ include "hello-k8s.labels" . | nindent 4 }}
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>{{ .Values.pageTitle }}</title>
      </head>
      <body style="font-family: Arial; padding: 40px">
        <h1>{{ .Values.pageTitle }}</h1>
        <p><b>Message:</b> {{ .Values.message }}</p>
        <p><b>Build:</b> {{ .Values.buildInfo }}</p>
        <p><b>Release:</b> {{ .Release.Name }} / {{ .Chart.Name }} {{ .Chart.Version }}</p>
      </body>
    </html>
